#!/bin/sh

docker_run="docker run"

run_zookeeper="$docker_run -d -p $INPUT_ZOOKEEPER_PORT:2181 -e ALLOW_ANONYMOUS_LOGIN=yes bitnami/zookeeper:$INPUT_ZOOKEEPER_VERSION"
sh -c "$run_zookeeper"

run_kafka="$docker_run -d -p $INPUT_KAFKA_PORT:9092  $INPUT_KAFKA_PORT:29092 -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 -e ALLOW_PLAINTEXT_LISTENER=yes -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT  -e KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092 -e AFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:29092 -e KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT bitnami/kafka:$INPUT_KAFKA_VERSION"
sh -c "$run_kafka"
